server:
  port: 8090
spring:
  application:
    name: cardGame
  data:
    mongodb:
      uri: mongodb+srv://admin:Reto3@cluster0.o9brs.mongodb.net/cardgame?retryWrites=true&w=majority
      #uri: mongodb://localhost:27017/cardgame
  rabbbitmq:
    addressess: amqps://ruwhqudj:i_nOid9etqsRlwn3tk6trdDyWIx1ws6H@jackal.rmq.cloudamqp.com/ruwhqudj
    #addressess: amqps://localhost:5672/
