server:
  port: 8080
spring:
  application:
    name: cardGame
  data:
    mongodb:
      uri: mongodb+srv://admin:Reto3@cluster0.o9brs.mongodb.net/cardgame?retryWrites=true&w=majority
      #uri: mongodb://localhost:27017/cardgame
  rabbbitmq:
    addressess: amqps://kvhbgmed:DuXOBwLGBBVMTyC23_tx8uhrsJZfb7Xd@stingray.rmq.cloudamqp.com/kvhbgmed
    #addressess: amqps://localhost:5672/
