server:
  port: 8090
spring:
  application:
    name: cardGame
  data:
    mongodb:
      uri: mongodb+srv://admin:Reto3@cluster0.o9brs.mongodb.net/cardgame?retryWrites=true&w=majority
      #uri: mongodb://localhost:27017/cardgame
  rabbbitmq:
    addressess: amqps://ayhynvzw:zC-RHutoDLtAE_h2H26Z8WP4w0nsppSy@jackal.rmq.cloudamqp.com/ayhynvzw
    #addressess: amqps://localhost:5672/
